### ISSUE TITLE
Change request: more flexibility with markup

### ISSUE THREAD

**Issue by openstaxalina** [katalysteducation/elefind#3]
We noted that sometimes Elefind found results that used single _or_ double quotes; other times, it would **_only_** find results with one or the other.  Examples:
[data-type="newline"] 
vs
[data-type='newline'] 

Is there a reason for this?  Is it possible to find results, regardless of what type of quotation mark is used?  Or was there another error unrelated to the markup?

There are likely other instances where the search could have more flexibility; however, for this regression test, we only searched using the markup above.

**Comment by PiotrKozlowski** [comment]
@openstaxalina Now all single quotation marks are change to double quotation marks.

**Comment by openstaxalina** [comment]
Thank you @PiotrKozlowski !
