### ISSUE TITLE
Bug: AP Macro 2e not found

### ISSUE THREAD

**Issue by openstaxalina** [katalysteducation/elefind#5]
When we search for markup in Principles of Macroeconomics for AP Courses 2e, we get the following result:

`Couldn't find any book with the name Principles of Macroeconomics for AP Courses 2e. Maybe this book is not yet avaible for searching custom elements.`

**Comment by PiotrKozlowski** [comment]
@openstaxalina There was typo in book name on the server. Now it's available.

**Comment by openstaxalina** [comment]
Thank you @PiotrKozlowski !

**Comment by omehes** [comment]
Verified. Fixed
